name: Archive Changed Files

on:
  push:
    branches:
      - main

jobs:
  archive_changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Ensures the last two commits are fetched

    - name: Archive Changes
      run: git archive -o update.zip HEAD $(git diff --name-only HEAD^)

    - name: Upload Archive
      uses: actions/upload-artifact@v4
      with:
        name: update-zip
        path: update.zip
